FROM alpine
RUN <<EOS
echo https://dl-cdn.alpinelinux.org/alpine/v3.14/main >> /etc/apk/repositories
apk --no-cache add git mariadb=10.5.19-r0 mariadb-client=10.5.19-r0 php84-dom php84-fileinfo php84-intl php84-mbstring php84-pdo_mysql php84-phar php84-session php84-tokenizer php84-xml php84-xmlwriter
cat <<-EOF > ~/entrypoint.sh
	composer install
	test -d /var/lib/mysql/mysql
	db_setup=\$?
	if [ "\$db_setup" = 1 ]; then
		mariadb-install-db --datadir=/var/lib/mysql --user=mysql
	fi
	mariadbd-safe &
	if [ "\$db_setup" = 1 ]; then
		while ! mariadb -e 'SELECT 1;'; do
			sleep 1;
		done
		mariadb -e 'CREATE DATABASE dev_db;
			GRANT ALL PRIVILEGES ON dev_db.* TO dev_user@localhost IDENTIFIED BY "dev_pass";'
		php artisan migrate
	fi
	if [ \`grep ^APP_KEY= .env\` = APP_KEY= ]; then
		php artisan key:generate
	fi
	php artisan serve --host=0.0.0.0
	EOF
ln -s /usr/bin/php84 /usr/local/bin/php
git config --global safe.directory /workspace
mkdir -p /workspace/storage/framework/cache/data
mkdir -p /workspace/storage/framework/sessions
mkdir -p /workspace/storage/framework/testing
mkdir -p /workspace/storage/framework/views
wget -O - https://getcomposer.org/installer | php -- --filename /usr/local/bin/composer
wget -O - https://raw.githubusercontent.com/reviewdog/reviewdog/fd59714416d6d9a1c0692d872e38e7f8448df4fc/install.sh | sh -s -- -b /usr/local/bin v0.18.1
EOS
WORKDIR /workspace
ENTRYPOINT ["sh", "/root/entrypoint.sh"]
