FROM alpine
RUN <<EOS
echo https://dl-cdn.alpinelinux.org/alpine/v3.14/main >> /etc/apk/repositories
apk --no-cache add apache2 apache2-proxy composer git mariadb=10.5.19-r0 mariadb-client=10.5.19-r0 php83-fpm php83-pdo_mysql
cat <<-EOF > /etc/apache2/conf.d/php.conf
	AddType text/html .php
	DirectoryIndex index.php
	<LocationMatch \.php\$>
		SetHandler "proxy:unix:/run/php-fpm.sock|fcgi://localhost"
	</LocationMatch>
	EOF
cat <<-EOF > /etc/php83/php-fpm.d/z.conf
	listen = /run/php-fpm.sock
	listen.owner = apache
	EOF
cat <<-EOF > ~/entrypoint.sh
	test -d /var/lib/mysql/mysql
	db_setup=\$?
	if [ "\$db_setup" = 1 ]; then
		mariadb-install-db --datadir=/var/lib/mysql --user=mysql
	fi
	mariadbd-safe &
	if [ "\$db_setup" = 1 ]; then
		while ! mariadb -e 'SELECT 1;'; do
			sleep 1;
		done
		mariadb -e 'CREATE DATABASE dev_db;
			GRANT ALL PRIVILEGES ON dev_db.* TO dev_user@localhost IDENTIFIED BY "dev_pass";'
	fi
	httpd -DFOREGROUND & php-fpm83 & wait
	EOF
git config --global safe.directory /mnt/repo
sed -i s!var/www/localhost/htdocs!mnt/repo/dist!g /etc/apache2/httpd.conf
wget -O - https://raw.githubusercontent.com/reviewdog/reviewdog/fd59714416d6d9a1c0692d872e38e7f8448df4fc/install.sh | sh -s -- -b /usr/local/bin v0.18.1
EOS
WORKDIR /mnt/repo
ENTRYPOINT ["sh", "/root/entrypoint.sh"]
