FROM alpine
RUN <<EOS
echo https://dl-cdn.alpinelinux.org/alpine/v3.14/main >> /etc/apk/repositories
apk --no-cache add composer git mariadb=10.5.19-r0 mariadb-client=10.5.19-r0 php83 php83-dom php83-fileinfo php83-pdo_mysql php83-session php83-tokenizer php83-xml php83-xmlwriter
cat <<-EOF > ~/entrypoint.sh
	composer install
	test -d /var/lib/mysql/mysql
	db_setup=\$?
	if [ "\$db_setup" = 1 ]; then
		mariadb-install-db --datadir=/var/lib/mysql --user=mysql
	fi
	mariadbd-safe &
	if [ "\$db_setup" = 1 ]; then
		while ! mariadb -e 'SELECT 1;'; do
			sleep 1;
		done
		mariadb -e 'CREATE DATABASE dev_db;
			GRANT ALL PRIVILEGES ON dev_db.* TO dev_user@localhost IDENTIFIED BY "dev_pass";'
		php artisan migrate
	fi
	php artisan serve --host=0.0.0.0
	EOF
git config --global safe.directory /workspace
mkdir -p /workspace/storage/framework/cache/data
mkdir -p /workspace/storage/framework/sessions
mkdir -p /workspace/storage/framework/testing
mkdir -p /workspace/storage/framework/views
wget -O - https://raw.githubusercontent.com/reviewdog/reviewdog/fd59714416d6d9a1c0692d872e38e7f8448df4fc/install.sh | sh -s -- -b /usr/local/bin v0.18.1
EOS
WORKDIR /workspace
ENTRYPOINT ["sh", "/root/entrypoint.sh"]
