name: Pull Requestの自動確認

on: [pull_request]

jobs:
  prettier:
    name: npm iとPrettierの実行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: technote-space/get-diff-action@v6
      - run: npm i
      - run: npx prettier --ignore-unknown --write ${{env.GIT_DIFF}}
        if: env.GIT_DIFF
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_author: ${{github.actor_id != 29139614 && format('{0} <{1}+{0}', github.actor, github.actor_id) || 'github-actions[bot] <41898282+github-actions[bot]'}}@users.noreply.github.com>
          commit_message: npm iとPrettierの実行結果を適用
  review:
    name: Reviewdogによる自動レビュー
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: mkdir -p storage/framework/{cache/data,sessions,testing,views}
      - run: composer install
      - run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/fd59714416d6d9a1c0692d872e38e7f8448df4fc/install.sh | sh -s -- -b . v0.18.1
      - run: npm ci
      - run: npm run review ${{secrets.GITHUB_TOKEN}}
  phpunit:
    name: PHPUnitによる自動テスト
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb:10.5
        env:
          MARIADB_DATABASE: dev_db
          MARIADB_USER: dev_user
          MARIADB_PASSWORD: dev_pass
          MARIADB_RANDOM_ROOT_PASSWORD: 1
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v5
      - run: |
          env=`cat .env.example`
          echo "${env/DB_HOST=localhost/DB_HOST=127.0.0.1}" > .env
      - run: mkdir -p storage/framework/{cache/data,sessions,testing,views}
      - run: composer install
      - run: npm ci
      - run: npm run build
      - run: php artisan key:generate
      - run: php artisan migrate
      - run: composer test
