name: Prettierによる自動整形

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: technote-space/get-diff-action@v6
      - run: npm i
      - run: npx prettier --ignore-unknown --write ${{ env.GIT_DIFF }}
        if: env.GIT_DIFF
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Prettierによる整形を適用
