name: Reviewdogによる自動レビュー

on: ["pull_request"]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-setup@v1
      - run: npm i
      - run: npx tsx src/ci/reviewdog.ts ${{ secrets.GITHUB_TOKEN }}
